-- config.lua
-- conky CPU & Memory load bars widget
-- by @rizado
-- 5 August 2025

config = {
    boxes = {
        {
            type = "background",
            x = 0,
            y = 0,
            w = 740,
            h = 240,
            centre_x = true,
            corners = { 8, 8, 8, 8 },
            rotation = 0,
            skew_x = 0, 
            skew_y = 0,
            draw_me = true,
            colour = { { 1, 0x000000, 0.5 } },
        },
    },
    bars = {
        {
            name = "cpu",
            arg = "cpu0",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 20,
            y = 170,
            height = 2,
            width = 40,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu1",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 80,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu2",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 130,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu3",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 180,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu4",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 230,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu5",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 280,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu6",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 330,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu7",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 380,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu8",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 430,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu9",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 480,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu10",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 530,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu11",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 580,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "cpu",
            arg = "cpu12",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 630,
            y = 170,
            height = 2,
            width = 30,
            blocks = 50,
            space = 1,
            angle = 0,
        },

        {
            name = "memperc",
            arg = "",
            max = 100,
            alarm = 90,
            bg_colour = { 0x00ff00, 0.333 },
            fg_colour = { 0x00FF00, 1 },
            mid_colour = { { 0.7, 0x00ff11, 1 }, { 0.7, 0xffff00, 1 }, { 0.9, 0xffff00, 1 }, { 0.9, 0xFF0000, 1 } },
            alarm_colour = { 0xff0000, 0.5 },
            smooth = true,
            x = 680,
            y = 170,
            height = 2,
            width = 40,
            blocks = 50,
            space = 1,
            angle = 0,
        },
    },
    rings = {
    },
    texts = {
        {
            text = "CPU",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 40,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu0}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 40,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 1",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 95,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu1}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 95,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 2",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 145,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu2}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 145,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 3",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 195,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu3}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 195,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 4",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 245,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu4}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 245,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 5",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 295,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu5}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 295,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 6",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 345,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu6}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 345,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 7",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 395,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu7}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 395,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 8",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 445,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu8}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 445,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 9",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 495,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu9}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 495,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 10",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 545,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu10}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 545,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 11",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 595,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu11}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 595,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 12",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 645,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu12}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 645,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "MEM",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 700,
            y = 185,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${memperc}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 700,
            y = 210,
            colour = { { 0, 0xFFFFFF, 1 } },
        },
    }
}

return config
