-- config.lua
-- conky CPU & Memory load rings widget
-- by @rizado
-- 5 August 2025

config = {
    boxes = {
        {
            type = "background",
            x = 0,
            y = 0,
            w = 740,
            h = 240,
            centre_x = false,
            corners = { 8, 8, 8, 8 },
            rotation = 0,
            skew_x = 0,
            skew_y = 0,
            draw_me = true,
            color = { { 1, 0x000000, 0.5 } },
        },
    },
    bars = {
    },
    rings = {
        {
            name = "cpu",
            arg = "cpu1",
            max = 100,
            xc = 70,
            yc = 60,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu2",
            max = 100,
            xc = 190,
            yc = 60,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu3",
            max = 100,
            xc = 310,
            yc = 60,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu4",
            max = 100,
            xc = 430,
            yc = 60,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu5",
            max = 100,
            xc = 550,
            yc = 60,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu6",
            max = 100,
            xc = 670,
            yc = 60,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu7",
            max = 100,
            xc = 70,
            yc = 180,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu8",
            max = 100,
            xc = 190,
            yc = 180,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu9",
            max = 100,
            xc = 310,
            yc = 180,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu10",
            max = 100,
            xc = 430,
            yc = 180,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu11",
            max = 100,
            xc = 550,
            yc = 180,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "cpu",
            arg = "cpu12",
            max = 100,
            xc = 670,
            yc = 180,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_color1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_color1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
    },
    texts = {
        {
            text = "CPU 1",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 70,
            y = 50,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu1}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 70,
            y = 65,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 2",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 190,
            y = 50,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu2}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 190,
            y = 65,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 3",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 310,
            y = 50,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu3}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 310,
            y = 65,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 4",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 430,
            y = 50,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu4}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 430,
            y = 65,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 5",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 550,
            y = 50,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu5}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 550,
            y = 65,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 6",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 670,
            y = 50,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu6}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 670,
            y = 65,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 7",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 70,
            y = 170,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu7}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 70,
            y = 185,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 8",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 190,
            y = 170,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu8}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 190,
            y = 185,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 9",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 310,
            y = 170,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu9}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 310,
            y = 185,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 10",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 430,
            y = 170,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu10}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 430,
            y = 185,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 11",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 550,
            y = 170,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu11}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 550,
            y = 185,
            color = { { 0, 0xFFFFFF, 1 } },
        },

        {
            text = "CPU 12",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 670,
            y = 170,
            color = { { 0, 0xFFFFFF, 1 } },
        },
        {
            text = "${cpu cpu12}%",
            font_name = "Ubuntu",
            font_size = 14,
            v_align = "t",
            h_align = "c",
            x = 670,
            y = 185,
            color = { { 0, 0xFFFFFF, 1 } },
        },
    }
}

return config
