-- config.lua
-- conky file system load widget
-- by @rizado
-- 5 August 2025

config = {
    boxes = {
        {
            type = "background",
            x = 0,
            y = 0,
            w = 400,
            h = 240,
            centre_x = true,
            corners = { 8, 8, 8, 8 },
            rotation = 0,
            skew_x = 0,
            skew_y = 0,
            draw_me = true,
            colour = { { 1, 0x000000, 0.5 } },
        },
    },
    bars = {
    },
    rings = {
        {
            name = "fs_used_perc",
            arg = "/",
            max = 100,
            xc = 70,
            yc = 100,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_colour1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_colour1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "fs_used_perc",
            arg = "/home",
            max = 100,
            xc = 200,
            yc = 100,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_colour1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_colour1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
        {
            name = "fs_used_perc",
            arg = "/mnt/media",
            max = 100,
            xc = 330,
            yc = 100,
            thickness = 20,
            radius = 50,
            sectors = 50,
            start_angle = -150,
            end_angle = 150,
            bg_colour1 = { { 0, 0x00ff00, 0.15 }, { 1, 0x00ff00, 0.15 } },
            fg_colour1 = { { 0, 0x00ff00, 1 }, { 1, 0x00ff00, 1 } },
            fill_sector = true,
        },
    },
    texts = {
        {
            text = "File systems using",
            font_name = "Ubuntu",
            font_size = 20,
            bold = true,
            x = 200,
            y = 15,
            h_align = "c",
            v_align = "t",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "${fs_used_perc /}%",
            font_name = "Ubuntu",
            font_size = 16,
            x = 70,
            y = 100,
            h_align = "c",
            v_align = "m",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "${fs_used_perc /home}%",
            font_name = "Ubuntu",
            font_size = 16,
            x = 200,
            y = 100,
            h_align = "c",
            v_align = "m",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "${fs_used_perc /mnt/media}%",
            font_name = "Ubuntu",
            font_size = 16,
            x = 330,
            y = 100,
            h_align = "c",
            v_align = "m",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "/",
            font_name = "Ubuntu",
            font_size = 14,
            x = 70,
            y = 170,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "/home",
            font_name = "Ubuntu",
            font_size = 14,
            x = 200,
            y = 170,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "/mnt/media",
            font_name = "Ubuntu",
            font_size = 14,
            x = 330,
            y = 170,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "Used: ${fs_used /}",
            font_name = "Ubuntu",
            font_size = 14,
            x = 70,
            y = 195,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "Used: ${fs_used /home}",
            font_name = "Ubuntu",
            font_size = 14,
            x = 200,
            y = 195,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "Used: ${fs_used /mnt/media}",
            font_name = "Ubuntu",
            font_size = 14,
            x = 330,
            y = 195,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "Size: ${fs_size /}",
            font_name = "Ubuntu",
            font_size = 14,
            x = 70,
            y = 220,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
        {
            text = "Size: ${fs_size /home}",
            font_name = "Ubuntu",
            font_size = 14,
            x = 200,
            y = 220,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        }, 
        {
            text = "Size: ${fs_size /mnt/media}",
            font_name = "Ubuntu",
            font_size = 14,
            x = 330,
            y = 220,
            h_align = "c",
            v_align = "b",
            colour = { { 1, 0xFFFFFF, 1 } },   
        },
    }
}

return config
