-- config.lua
-- conky processes list widget
-- by @rizado
-- 16 August 2025

config = {
    boxes = {
        {
            type = "background",
            x = 0,
            y = 0,
            w = 400,
            h = 240,
            corners = { 8, 8, 8, 8 },
            rotation = 0,
            skew_x = 0,
            skew_y = 0,
            draw_me = true,
            color = { { 1, 0x000000, 0.5 } },
        },
    },
    bars = {
    },
    rings = {
    },
    texts = {
        {
            text = "Top processes",
            font_name = "Ubuntu",
            font_size = 20,
            bold = true,
            x = 200,
            y = 15,
            h_align = "c",
            v_align = "t",
            color = { { 1, 0xFFFFFF, 1 } },
        },

        {
            text = "Name",
            font_name = "Ubuntu",
            font_size = 14,
            bold = true,
            x = 40,
            y = 60,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0xFFFFFF, 1 } },
        },
        {
            text = "1:  ${top name 1}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 80,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0xFF0000, 1 } },
        },
        {
            text = "2:  ${top name 2}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 100,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "3:  ${top name 3}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 120,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "4:  ${top name 4}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 140,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "5:  ${top name 5}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 160,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "6:  ${top name 6}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 180,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "7:  ${top name 7}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 200,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "8:  ${top name 8}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 20,
            y = 220,
            h_align = "l",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },

        {
            text = "PID",
            font_name = "Ubuntu",
            font_size = 14,
            bold = true,
            x = 220,
            y = 60,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFFFF, 1 } },
        },
        {
            text = "${top pid 1}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 80,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFF0000, 1 } },
        },
        {
            text = "${top pid 2}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 100,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "${top pid 3}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 120,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "${top pid 4}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 140,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top pid 5}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 160,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top pid 6}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 180,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top pid 7}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 200,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top pid 8}",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 220,
            y = 220,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },

        {
            text = "CPU",
            font_name = "Ubuntu",
            font_size = 14,
            bold = true,
            x = 300,
            y = 60,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFFFF, 1 } },
        },
        {
            text = "${top cpu 1} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 80,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFF0000, 1 } },
        },
        {
            text = "${top cpu 2} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 100,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "${top cpu 3} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 120,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "${top cpu 4} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 140,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top cpu 5} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 160,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top cpu 6} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 180,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top cpu 7} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 200,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top cpu 8} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 300,
            y = 220,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },

        {
            text = "MEM",
            font_name = "Ubuntu",
            font_size = 14,
            bold = true,
            x = 380,
            y = 60,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFFFF, 1 } },
        },
        {
            text = "${top mem 1} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 80,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFF0000, 1 } },
        },
        {
            text = "${top mem 2} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 100,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "${top mem 3} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 120,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0xFFFF00, 1 } },
        },
        {
            text = "${top mem 4} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 140,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top mem 5} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 160,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top mem 6} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 180,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top mem 7} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 200,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
        {
            text = "${top mem 8} %",
            font_name = "Ubuntu",
            font_size = 14,
            bold = false,
            x = 380,
            y = 220,
            h_align = "r",
            v_align = "b",
            color = { { 1, 0x00CC00, 1 } },
        },
    }
}

return config
